spring:
  application:
    name: ApiGateway
  cloud.gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Marketing-Service
          uri: lb://MarketingService
          predicates:
            - Path=/api/v1/**


server:
  port: 8084

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

