spring:
  application:
   name: MarketingService
  api:
    version: v1
server:
  port: 8086
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/